config/routes.rb
Rails.application.routes.draw do
  resources :collaborations, except: [:destroy]
  resources :notes
  devise_for :users

  root 'welcome#index'
  get 'welcome/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/includes/_foot.html.erb
<footer class="mt-3">
	<div class="container-fluid text-center mt-3">
		<div class="row justify-content-center bg-dark text-white p-3">
			<div class="col-md-6 text-white">
				<h6>LinkedIn_Accout</h6>
                <hr>
				<p><a href="https://www.linkedin.com/in/ahmed-abdelhamd/" class="btn btn-outline-primary text-white">Ahmed
					Abdelhamid</a></p>
			</div>
			<div class="col-md-6 text-white">
				<h6>GitHub_Accout</h6>
                <hr>
				<p><a href="https://github.com/Ahmed-Abd-elhamid" class="btn btn-outline-success text-white">Ahmed
					Abdelhamid</a></p>
			</div>
		</div>
		<div class="row justify-content-center bg-dark text-white pt-2 p-1">
			<div class="col-md-10 text-white">
				<h6 class="text-white">CopyRight &copy; <a href="https://github.com/Ahmed-Abd-elhamid/Note-app" class="btn btn-sm btn-primary text-white rounded shadow">note up</a></h6>
			</div>
		</div>
	</div>
</footer>

app/views/includes/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="container p-1 text-center shadow rounded alert alert-<%= key %> <% if key == 'alert'%>alert-danger<% end %> <% if key == 'notice'%>alert-success<% end %> mt-2">
    <h6 class="d-inline"><strong><%= key %>:</strong> <%= value %></h6>
    <a href="#" data-dismiss="alert" class="close text-right text-dark">×</a>
  </div>
<% end %>

app/views/includes/_navigation.html.erb
<nav class="navbar navbar-dark navbar-static-top navbar-expand-md bg-dark p-1 mb-3" id="top">
    <div class="container-fluid">
        <button class="navbar-toggler ml-2" type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav mr-auto">
                <li class='nav-item p-1 rounded'>
                    <%= link_to welcome_index_path, class: 'nav-link text-white btn-outline-primary rounded btn-md' do %>
                        <%= fa_icon "home", class: 'text-white' %>
                        <span>Home</span>
                    <%end%>
                </li>  

                <li class='nav-item p-1 rounded'>
                    <%= link_to notes_path, class: 'nav-link text-white btn-outline-warning rounded btn-md' do %>
                        <span>Note</span>
                    <%end%>
                </li>
                <li class='nav-item p-1 rounded'>
                    <%= link_to collaborations_path, class: 'nav-link text-white btn-outline-warning rounded btn-md' do %>
                        <span>Collaboration</span>
                    <%end%>
                </li>
            <% if current_user %>
            <% end %>
            </ul>
            <ul class="nav navbar-nav ml-auto">
            <% if current_user %>
                <li class='nav-item p-1 rounded'>
                    <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-white btn-outline-danger rounded btn-md' do %>
                        <span>Sign Out</span>
                    <%end%>
                </li>
            <%else%>
                <li class='nav-item p-1 rounded'>
                    <%= link_to new_user_registration_path, class: 'nav-link text-white btn-outline-info rounded btn-md' do %>
                        <span>Sign Up</span>
                    <%end%>
                </li>
                <li class='nav-item p-1 rounded'>
                    <%= link_to new_user_session_path, class: 'nav-link text-white btn-outline-success rounded btn-md' do %>
                        <span>Sign In</span>
                    <%end%>
                </li>
            <% end %>     
            </ul>
        </div>
    </div>
</nav>