config/routes.rb
Rails.application.routes.draw do
  resources :collaborations, except: [:destroy]
  resources :notes
  devise_for :users

  root 'welcome#index'
  get 'welcome/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/collaboration.rb
class Collaboration < ApplicationRecord
  belongs_to :note
  belongs_to :user
end

app/controllers/collaborations_controller.rb
class CollaborationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_note_vaidate, only: [:create]
  before_action :set_note_collaboration, only: [:show, :edit, :update, :destroy]
  # before_action :authorize_user, only: [:create]

  # GET /collaborations
  # GET /collaborations.json
  def index
    @collaborations = Collaboration.where(user_id: current_user.id)
    if params[:q]
      @collaborations = @collaborations.joins(:note).where('lower(title) LIKE :q OR lower(body) LIKE :q', q: "%#{params[:q].downcase}%")
    end
  end

  # GET /collaborations/1
  # GET /collaborations/1.json
  def show
  end

  # GET /collaborations/new
  def new
    @collaboration = Collaboration.new
  end

  # GET /collaborations/1/edit
  def edit
  end

  # POST /collaborations
  # POST /collaborations.json
  def create
    return render json: {:error => "unauthorized"}, status: :unauthorized if @note.nil? || @note.user_id == current_user.id
    return render json: {:error => "existed!"}, status: 400 unless Collaboration.where(user_id: current_user.id, note_id: @note.id).first.nil?

    @collaboration = Collaboration.new(user_id: current_user.id, note_id: @note.id, can_edit: false)

    respond_to do |format|
      if @collaboration.save
        format.html { redirect_to collaboration_path(@note), notice: 'Collaboration was successfully created.' }
        format.json { render :show, status: :created, location: @collaboration }
      else
        format.html { render :new }
        format.json { render json: @collaboration.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /collaborations/1
  # PATCH/PUT /collaborations/1.json
  def update
    return render json: {:error => "unauthorized"}, status: :unauthorized unless @collaboration.can_edit

    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collaborations/1
  # DELETE /collaborations/1.json
  def destroy
    return render json: {:error => "unauthorized"}, status: :unauthorized unless @collaboration.can_edit

    @collaboration.destroy
    respond_to do |format|
      format.html { redirect_to collaborations_url, notice: 'Collaboration was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collaboration
      @collaboration = Collaboration.find(params[:id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_note_collaboration
      @note = Note.find(params[:id])
      @collaboration = Collaboration.where(note_id: @note.id, user_id: current_user.id).first
    end

    def set_note_vaidate
      unless collaboration_params[:uuid].nil? and collaboration_params[:password].nil?
        @note = Note.where(uuid: collaboration_params[:uuid], password: collaboration_params[:password]).first
      end
    end

    # Only allow a list of trusted parameters through.
    def collaboration_params
      params.require(:collaboration).permit(:note_id, :user_id, :uuid, :password)
    end

    # Only allow a list of trusted parameters through.
    def note_params
      params.require(:note).permit(:title, :body)
    end

    def authorize_user
      return render json: {:error => "unauthorized"}, status: :unauthorized if @note.nil? || @note.user_id == current_user.id
      return render json: {:error => "existed!"}, status: 400 unless Collaboration.where(user_id: current_user.id, note_id: @note.id).first.nil?
    end
end

app/helpers/collaborations_helper.rb
module CollaborationsHelper
end

app/views/collaborations/_form.html.erb
<%= form_with(model: @note, url: "/collaborations/#{@note.id}", local: true) do |form| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
        <% @note.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/collaborations/edit.html.erb
<h1>Editing Collaboration</h1>

<%= render 'form', collaboration: @collaboration %>

<%= link_to 'Show', @collaboration %> |
<%= link_to 'Back', collaborations_path %>

app/views/collaborations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Collaborations</h1>

<div class="d-flex justify-content-center h-100">
  <form class="searchbar">
      <input class="search_input" type="text" name="q" placeholder="Search...">
      <button type="submit" class="search_icon"><i class="fa fa-search"></i></button>
  </form>
</div>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>User</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @collaborations.each do |collaboration| %>
      <tr>
        <td><%= collaboration.note.title %></td>
        <td><%= collaboration.note.body %></td>
        <td><%= collaboration.note.user.email %></td>
        <td><%= link_to 'Show', collaboration_path(collaboration.note) %></td>
        <td><%= link_to 'Edit', edit_collaboration_path(collaboration.note) if collaboration.can_edit %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/collaborations/new.html.erb
<div class="container">
    <div class="row justify-content-center">
        <div class="col-8 border m-4 p-2 rounded shadow">
        <h1>New Collaboration</h1>

        <%= form_with(model: @collaboration, local: true) do |form| %>
          <% if @collaboration.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@collaboration.errors.count, "error") %> prohibited this collaboration from being saved:</h2>

              <ul>
                <% @collaboration.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
            <%= form.hidden_field :uuid, value: params[:uuid] %>


        <div class="form-group">
            <%= form.label :password %>
            <%= form.text_field :password, class: "form-control" %>
          </div>
            <div class="actions">
            <%= form.submit %>
          </div>
        <% end %>

        <%= link_to 'Back', collaborations_path %>
        </div>
    </div>
</div>

app/views/collaborations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @note.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @note.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @note.user.email %>
</p>

<p>
  <strong>Collaborations:</strong>
    <% @note.collaborations.each do |collaboration| %>
      <%= collaboration.user.email %> - 
    <% end %>
</p>

<%= link_to 'Edit', edit_collaboration_path(@note) if @collaboration.can_edit %> |
<%= link_to 'Back', notes_path %>